# Generated by Django 4.2.1 on 2023-05-26 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("littleLemonAPI", "0002_alter_menu_item_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu_item", old_name="category_id", new_name="category",
        ),
    ]
